require:
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Exclude:
    - app/api/api/**/*.rb
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
