require:
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - lib/tasks/prog_image_tasks.rake
Metrics/LineLength:
  Max: 120

RSpec/AnyInstance:
  Enabled: false
RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Exclude:
    - app/api/prog_image/api/**/*.rb
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
